### ISSUE TITLE
Bug dealing with workingDirectory?

### ISSUE THREAD

**Issue by manwar** [saiftynet/EZPWC#4]
Hi @saiftynet 

I am creating the issue on behalf of Kevin Colyer:

>>
>> There is a bug on line 407(ish) of EZPWC.pl: the default config is not set with the 
>> $workingdirectory value. I think it should be:
>>
>>                workingDirectory     => $workingDirectory,

Just to let you know that I haven't verified it myself.

Best Regards,
Mohammad S Anwar

**Comment by saiftynet** [comment]
thanks mate

**Comment by saiftynet** [comment]
Fixed now...hopefully

**Comment by saiftynet** [comment]
How does Kevin submit his solutions (as he appears not to have a github
account?)

Best wishes

Saif

**Comment by manwar** [comment]
Kevin's github user name is "kevincolyer".

https://github.com/kevincolyer
