### ISSUE TITLE
my normal github username does not match my PWC username

### ISSUE THREAD

**Issue by kevincolyer** [saiftynet/EZPWC#6]
Can my PWC username be changed or aliased to my github user name! 
eg. I am kevin-colyer at PWC but kevincolyer for my github account

Is there a way to either change all my entries to match my normal github account or a way to alias it. Currently I make local directory links each week.

Great tool though! Thanks!

**Comment by saiftynet** [comment]
hi Kevin,

yes,1)  the latest version should  allow you to have different github and pwc usernames. It checks that the folder with your github name  exists. if not then should ask you to enter
your pwc username. Could you let me know if that works for you?
2) To change your PWC user name to your github username would require a chat with manwar...but that might render all links to your previous submissions in other pages (e.g. the reviews ) to become invalid.

saif

**Comment by kevincolyer** [comment]
Hi. The option is there but it just drops me into open a bug report...
